[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "don-pmm"
authors = [{name = "Mykola Kharechko", email = "crchemist@gmail.com"}]
dynamic = ["version", "description"]
